

export const routes = {
  order:4,
  routes: [
    {
      name: 'demo',
      path: '/demo',
      title: '功能示例',
      requiresAuth: true,
      icon: 'icon-park-outline:application-one',
      menuType: 'dir',
      componentPath: null,
      id: '13',
      pid: null,
    },
    {
      name: 'fetch',
      path: '/demo/fetch',
      title: '请求示例',
      requiresAuth: true,
      icon: 'icon-park-outline:international',
      componentPath: '/demo/fetch/index.vue',
      id: '5',
      pid: '13',
    },
    {
      name: 'echarts',
      path: '/demo/echarts',
      title: 'ECharts',
      requiresAuth: true,
      icon: 'icon-park-outline:chart-proportion',
      componentPath: '/demo/echarts/index.vue',
      id: '15',
      pid: '13',
    },
    {
      name: 'map',
      path: '/demo/map',
      title: '地图',
      requiresAuth: true,
      icon: 'carbon:map',
      keepAlive: true,
      componentPath: '/demo/map/index.vue',
      id: '17',
      pid: '13',
    },
    {
      name: 'editor',
      path: '/demo/editor',
      title: '编辑器',
      requiresAuth: true,
      icon: 'icon-park-outline:editor',
      menuType: 'dir',
      componentPath: null,
      id: '13-10',
      pid: '13',
    },
    {
      name: 'editorMd',
      path: '/demo/editor/md',
      title: 'MarkDown',
      requiresAuth: true,
      icon: 'ri:markdown-line',
      componentPath: '/demo/editor/md/index.vue',
      id: '13-10-3',
      pid: '13-10',
    },

    {
      name: 'editorRich',
      path: '/demo/editor/rich',
      title: '富文本',
      requiresAuth: true,
      icon: 'icon-park-outline:edit-one',
      componentPath: '/demo/editor/rich/index.vue',
      id: '13-10-2',
      pid: '13-10',
    },
  ]
 }
